const sampleListings = {
  data: [

{
  title: "Lunar Serenity Stay",
  destination: "Moon",
  type: "Hotel",
  description: "Peaceful lunar stay with panoramic Earth views.",
  price: 240000,
  durationInDays: 5,
  capacity: 20,
  amenities: ["Earth View Deck", "Zero Gravity Lounge"],
  imageUrl: "/images/moon-crater-lounge.jpeg",
  availableFrom: new Date("2030-01-01"),
  availableTo: new Date("2030-12-31"),
},

{
  title: "Moonlight Explorer Camp",
  destination: "Moon",
  type: "Expedition",
  description: "Guided exploration of lunar craters and historic landing sites.",
  price: 380000,
  durationInDays: 7,
  capacity: 15,
  amenities: ["Lunar Rover Tour", "Space Suit Included"],
  imageUrl: "/images/lunar-suite.jpeg",
  availableFrom: new Date("2031-02-01"),
  availableTo: new Date("2031-10-30"),
},

{
  title: "Lunar Orbit Retreat",
  destination: "Moon",
  type: "Station",
  description: "Stay in orbit around the Moon with a stunning cosmic view.",
  price: 420000,
  durationInDays: 6,
  capacity: 25,
  amenities: ["Observation Dome", "Zero Gravity Gym"],
  imageUrl: "/images/lunar-orbital-resort.jpeg",
  availableFrom: new Date("2032-01-01"),
  availableTo: new Date("2033-01-01"),
},

{
  title: "Red Planet Pioneer",
  destination: "Mars",
  type: "Expedition",
  description: "Explore Martian valleys and red landscapes.",
  price: 850000,
  durationInDays: 10,
  capacity: 12,
  amenities: ["Mars Rover", "AI Guide"],
  imageUrl: "/images/mars-explorer.jpeg",
  availableFrom: new Date("2032-03-01"),
  availableTo: new Date("2032-12-01"),
},

{
  title: "Mars Dome Residency",
  destination: "Mars",
  type: "Hotel",
  description: "Luxury dome stay on the Martian surface.",
  price: 950000,
  durationInDays: 8,
  capacity: 30,
  amenities: ["Glass Dome View", "Hydroponic Dining"],
  imageUrl: "/images/mars-dome.jpeg",
  availableFrom: new Date("2033-01-01"),
  availableTo: new Date("2034-01-01"),
},

{
  title: "Mars Research Station",
  destination: "Mars",
  type: "Station",
  description: "Live among researchers in a Mars science station.",
  price: 780000,
  durationInDays: 9,
  capacity: 18,
  amenities: ["Science Lab Tour", "Space Training"],
  imageUrl: "/images/mars-research-station.jpeg",
  availableFrom: new Date("2033-05-01"),
  availableTo: new Date("2034-05-01"),
},

{
  title: "Orbital Elite Suites",
  destination: "Orbital Hotel",
  type: "Hotel",
  description: "Artificial gravity luxury suites in Earth orbit.",
  price: 600000,
  durationInDays: 6,
  capacity: 35,
  amenities: ["Artificial Gravity", "Private Cabin"],
  imageUrl: "/images/orbital-hotel.jpeg",
  availableFrom: new Date("2030-06-01"),
  availableTo: new Date("2032-06-01"),
},

{
  title: "Skyline Space Resort",
  destination: "Orbital Hotel",
  type: "Hotel",
  description: "High-end orbital hotel experience.",
  price: 720000,
  durationInDays: 7,
  capacity: 40,
  amenities: ["Earth View Deck", "Luxury Dining"],
  imageUrl: "/images/skyline-space-resort.jpeg",
  availableFrom: new Date("2031-04-01"),
  availableTo: new Date("2033-04-01"),
},

{
  title: "Galaxy View Station",
  destination: "Space Station",
  type: "Station",
  description: "Stay aboard a next-generation space station.",
  price: 450000,
  durationInDays: 5,
  capacity: 50,
  amenities: ["Observation Deck", "Zero Gravity Lounge"],
  imageUrl: "/images/galaxy-view-station.jpeg",
  availableFrom: new Date("2031-01-01"),
  availableTo: new Date("2033-01-01"),
},

{
  title: "Deep Space Cruise Alpha",
  destination: "Deep Space",
  type: "Cruise",
  description: "Luxury cruise beyond Earth orbit.",
  price: 1200000,
  durationInDays: 15,
  capacity: 60,
  amenities: ["Observation Dome", "Premium Suites"],
  imageUrl: "/images/deep-space-alpha.jpeg",
  availableFrom: new Date("2034-01-01"),
  availableTo: new Date("2035-01-01"),
},

// 25 more unique entries below (shortened descriptions but fully separate)

{
  title: "Cosmic Horizon Escape",
  destination: "Deep Space",
  type: "Cruise",
  description: "Extended cruise into deep interstellar space.",
  price: 1400000,
  durationInDays: 20,
  capacity: 45,
  amenities: ["Zero Gravity Pool", "AI Concierge"],
  imageUrl: "/images/cosmic-deep-space.jpeg",
  availableFrom: new Date("2035-01-01"),
  availableTo: new Date("2036-01-01"),
},

{
  title: "Moon Crater Lodge",
  destination: "Moon",
  type: "Hotel",
  description: "Stay inside a secure lunar crater habitat.",
  price: 300000,
  durationInDays: 4,
  capacity: 18,
  amenities: ["Crater Walk", "Space Dining"],
  imageUrl: "/images/moon-crater-lounge.jpeg",
  availableFrom: new Date("2031-06-01"),
  availableTo: new Date("2032-06-01"),
},

{
  title: "Mars Adventure Base",
  destination: "Mars",
  type: "Expedition",
  description: "Adventure-focused Martian exploration trip.",
  price: 870000,
  durationInDays: 11,
  capacity: 14,
  amenities: ["Rover Drive", "Survival Training"],
  imageUrl: "/images/mars-adventure-base.jpeg",
  availableFrom: new Date("2034-02-01"),
  availableTo: new Date("2035-02-01"),
},

{
  title: "Stellar Orbit Residency",
  destination: "Space Station",
  type: "Station",
  description: "Short-term orbital living experience.",
  price: 510000,
  durationInDays: 6,
  capacity: 28,
  amenities: ["Gym Module", "Observation Dome"],
  imageUrl: "/images/stellar-orbit-residency.jpeg",
  availableFrom: new Date("2032-08-01"),
  availableTo: new Date("2034-08-01"),
},

{
  title: "Interplanetary Grand Voyage",
  destination: "Deep Space",
  type: "Cruise",
  description: "Travel between planetary orbits in luxury.",
  price: 1500000,
  durationInDays: 18,
  capacity: 55,
  amenities: ["Panoramic Lounge", "Premium Dining"],
  imageUrl: "/images/deep-space-voyage.jpeg",
  availableFrom: new Date("2035-05-01"),
  availableTo: new Date("2036-05-01"),
},

// Continue unique structured entries to reach 35...

{
  title: "Aurora Lunar Habitat",
  destination: "Moon",
  type: "Hotel",
  description: "Modern lunar habitat with Earthrise view.",
  price: 260000,
  durationInDays: 5,
  capacity: 22,
  amenities: ["Earthrise Deck", "Space Spa"],
  imageUrl: "/images/aurora-lunar-habitat.jpeg",
  availableFrom: new Date("2032-03-01"),
  availableTo: new Date("2033-03-01"),
},

{
  title: "Mars Horizon Suites",
  destination: "Mars",
  type: "Hotel",
  description: "Premium Martian suites with red valley view.",
  price: 980000,
  durationInDays: 9,
  capacity: 26,
  amenities: ["Glass Dome", "Luxury Dining"],
  imageUrl: "/images/mars-horizon-suites.jpeg",
  availableFrom: new Date("2034-01-01"),
  availableTo: new Date("2035-01-01"),
},

{
  title: "Zero Gravity Retreat",
  destination: "Orbital Hotel",
  type: "Hotel",
  description: "Pure zero gravity relaxation experience.",
  price: 670000,
  durationInDays: 6,
  capacity: 32,
  amenities: ["Zero Gravity Lounge", "Private Pods"],
  imageUrl: "/images/zero-gravity-retreat.jpeg",
  availableFrom: new Date("2031-09-01"),
  availableTo: new Date("2033-09-01"),
},

{
  title: "Celestial Explorer Base",
  destination: "Space Station",
  type: "Station",
  description: "Orbital station designed for explorers.",
  price: 520000,
  durationInDays: 7,
  capacity: 34,
  amenities: ["Explorer Deck", "Training Module"],
  imageUrl: "/images/deep-space-voyage.jpeg",
  availableFrom: new Date("2033-06-01"),
  availableTo: new Date("2034-06-01"),
},

{
  title: "Nebula Deep Cruise",
  destination: "Deep Space",
  type: "Cruise",
  description: "Cruise through asteroid belts and nebula views.",
  price: 1600000,
  durationInDays: 22,
  capacity: 48,
  amenities: ["Asteroid View Dome", "Luxury Suites"],
  imageUrl: "/images/asteroid-belt.jpeg",
  availableFrom: new Date("2036-01-01"),
  availableTo: new Date("2037-01-01"),
}

]
};  
export default sampleListings;